another trail from fresh

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -2,7 +2,8 @@ name: Deploy
 
 on:
   push:
-    branches: ['master']
+    branches:
+      - master
 
 jobs:
   build:
@@ -15,14 +16,14 @@ jobs:
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        run: |
-          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
+        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
 
       - name: Create .env file
         run: |
-          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
-          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
-          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
+          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
+          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
+          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
+          echo "POSTGRES_HOSTNAME=${{ secrets.POSTGRES_HOSTNAME }}" >> .env
 
       - name: Build the Docker image
         run: docker-compose build web
@@ -31,14 +32,22 @@ jobs:
         run: docker images
 
       - name: Tag the Docker image
-        run: docker tag web:latest ${{ secrets.DOCKER_USERNAME }}/recipe-api-img:latest
+        run: |
+          IMAGE_ID=$(docker images -q web:latest)
+          echo "Image ID: $IMAGE_ID"
+          if [ -z "$IMAGE_ID" ]; then
+            echo "Image web:latest not found!"
+            exit 1
+          fi
+          docker tag web:latest ${{ secrets.DOCKER_USERNAME }}/web:latest
 
       - name: Push the Docker image
-        run: docker push ${{ secrets.DOCKER_USERNAME }}/recipe-api-img:latest
+        run: docker push ${{ secrets.DOCKER_USERNAME }}/web:latest
 
   start:
     runs-on: self-hosted
     needs: build
+
     steps:
       - uses: actions/checkout@v3
 
@@ -46,25 +55,22 @@ jobs:
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        run: |
-          echo $DOCKER_PASSWORD | sudo docker login --username $DOCKER_USERNAME --password-stdin
+        run: echo $DOCKER_PASSWORD | sudo docker login --username $DOCKER_USERNAME --password-stdin
 
       - name: Pull the Docker image
-        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/recipe-api-img:latest
-
-      - name: Tagging new docker image as recipe-api-img
-        run: sudo docker tag ${{ secrets.DOCKER_USERNAME }}/recipe-api-img:latest recipe-api-img:latest
+        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/web:latest
 
       - name: Create .env file
         run: |
-          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
-          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
-          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
+          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
+          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
+          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
+          echo "POSTGRES_HOSTNAME=${{ secrets.POSTGRES_HOSTNAME }}" >> .env
 
       - name: Run the Docker image with compose in detached mode
         run: sudo docker-compose up -d
 
-      - name: Check the Docker image
+      - name: Check the Docker container
         run: sudo docker ps
 
       - name: Log latest data
